# MQTT Bridge Configuration for Hello World Node
mqtt_broker_host: "localhost"
mqtt_broker_port: 1883
mqtt_topic_prefix: "ros2"
mqtt_client_id: "hello_world_bridge"
mqtt_username: ""
mqtt_password: ""
